version: "3.8"

services:

###

  ubuntu2004_python3:
    profiles: [never]
    image: ubuntu2004:python3-10
    environment:
    - TZ
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:20.04

        ENV TZ $TZ
        #RUN date
        RUN apt update
        RUN apt install -y software-properties-common
        RUN add-apt-repository ppa:deadsnakes/ppa
        RUN apt install -y python3.10 curl gpg
        WORKDIR /tmp
        ADD https://bootstrap.pypa.io/get-pip.py .
        RUN python3.10 get-pip.py

        ENTRYPOINT []
        CMD ["sleep","infinity"]
